apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-sync-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-sync-app
  template:
    metadata:
      labels:
        app: inventory-sync-app
    spec:
      containers:
        - name: inventory-sync-app
          image: klalithyaa/inventory-sync-system:latest
          ports:
            - containerPort: 8086